name: BIST 100 Daily Update

on:
  schedule:
    # Günde bir kez çalıştırmak için ayar: gece yarısı (00:00)
    - cron: "0 0 * * *"
  workflow_dispatch:  # Manuel çalıştırma tetikleyicisi

jobs:
  update_bist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run BIST update script
      run: |
        python main.py
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
